/* Code generated by asmc from file Led2Sm.sm, do not edit. */

 #include "led.h" 

#include "Led2Sm.h"

Led2Sm::Led2Sm()
{
  state = led_off;
}

void Led2Sm::begin()
{
}

Led2Sm::retstatus_t Led2Sm::run(event_t event)
{
  state_t next_state;
  int handled = 0;

  switch(state) {
  case led_off:

    /* Perform state exit actions. */
    if ((event == BUTTON_PRESSED)) {
 ledOn(); 
    }

    if (event == BUTTON_PRESSED) {
      handled = 1;
      next_state = led_on;
    }
    break;

  case led_on:

    if (event == BUTTON_PRESSED) {
      handled = 1;
      next_state = led_off;
    }
    break;

  } /* switch */

  if (!handled) {
    return unhandled_event;
  }

  if (next_state) {
    state = next_state;
  }

  return ok;
}

