/* Code generated by fsmc from file telephone.fsm, do not edit. */

#ifndef _TELEPHONE-FSM_H_
 #define _TELEPHONE-FSM_H_

#define DIGIT 1
#define LOOP_TIMER 2
#define OFF_HOOK_TIMER 3
#define RING_TIMER 4
#define CLOCK_TIMER 5
#define INVALID_DIGIT 6
#define PLAYBACK_DONE 7
#define INVALID_NUMBER 8
#define LINE_BUSY 9
#define DEPOSIT_MONEY 10
#define TIME 11
#define NYC_TEMP 12
#define EMERGENCY 13
#define DIALING_DONE 14
#define LEFT_OFF_HOOK 15
#define OFF_HOOK 16
#define ON_HOOK 17

class telephone-fsm {
  public:
    telephone-fsm();
    void begin();
    int run(int event);
};

#endif /* _TELEPHONE-FSM_H_ */

