/* Code generated by fsmc from file telephone.fsm, do not edit. */

#ifndef _TELEPHONE_FSM_H_
#define _TELEPHONE_FSM_H_

class telephone_fsm {
  public:

    // State machine events
    typedef enum {
      DIGIT,
      LOOP_TIMER,
      OFF_HOOK_TIMER,
      RING_TIMER,
      CLOCK_TIMER,
      INVALID_DIGIT,
      PLAYBACK_DONE,
      INVALID_NUMBER,
      LINE_BUSY,
      DEPOSIT_MONEY,
      TIME,
      NYC_TEMP,
      EMERGENCY,
      DIALING_DONE,
      LEFT_OFF_HOOK,
      OFF_HOOK,
      ON_HOOK
    } state_t;

    // Return codes for run function.
    typedef enum {
      ok,
      unknown_event,
      unhandled_event
    } retstatus_t;

    telephone_fsm();
    void begin();
    retstatus_t run(event_t event);

  private:

    // Possiable states.
    typedef enum {
      WaitForOnHook,
      InvalidDigit,
      LeftOffHook,
      MessagePlayed,
      PlayingMessage,
      BusySignal,
      DepositMoney,
      Time,
      NYCTemp,
      Routing,
      Dialing,
      OnHook
    } state_t;

    state_t state;
};

#endif /* _TELEPHONE_FSM_H_ */

