/* Code generated by asmc from file LedSm.sm, do not edit. */

 #include "led.h" 

#include "LedSm.h"

LedSm::LedSm()
{
  state = led_off;
}

void LedSm::begin()
{
}

LedSm::retstatus_t LedSm::run(event_t event)
{
  state_t next_state;
  int handled = 0;

  switch(state) {
  case led_off:

    if (event == BUTTON_PRESSED) {
      handled = 1;
      next_state = led_on;
 ledOn(); 
    }
    break;

  case led_on:

    if (event == BUTTON_PRESSED) {
      handled = 1;
      next_state = led_off;
 ledOff(); 
    }
    break;

  } /* switch */

  if (!handled) {
    return unhandled_event;
  }

  if (next_state) {
    state = next_state;
  }

  return ok;
}

