/* Code generated by asmc from file LedSm.sm, do not edit. */

#ifndef _LEDSM_H_
#define _LEDSM_H_

class LedSm {
  public:

    // State machine events
    typedef enum {
      BUTTON_PRESSED
    } event_t;

    // Return codes for run function.
    typedef enum {
      ok,
      unknown_event,
      unhandled_event
    } retstatus_t;

    LedSm();
    void begin();
    retstatus_t run(event_t event);

  private:

    // Possiable states.
    typedef enum {
      led_off,
      led_on
    } state_t;

    state_t state;
};

#endif /* _LEDSM_H_ */

